submenu
iGEM-UTokyo/igem-site pull request #21
Opened 2021-09-09 05:52 UTC by niimi213

2021-09-09 10:08 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +      li(v-for = "item in items" :href="item.url" style={"list-style": "none"})
ナビゲーションに関する情報はクライアント側でも持つかは議論したいところですね

2021-09-16 07:27 UTC, shundroid requested changes

2021-09-16 07:27 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +          span(:class=`{ active:isOpen==='${i}'}`)
`isOpen` という変数名はbool値に用いることが多いので、 変数名を変えた方がいい気がします(`activeMenu` などでしょうか。他にいいのあったらそれにしてください)。

2021-09-16 07:27 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +          a(href=theme.menu[i].link @mouseover=`subMenu('${i}')`) #{i}
`submenu` という表記で用いている箇所があるので、Mは小文字で統一してほしいです

2021-09-16 07:27 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +          a(href=theme.menu[i].link @mouseover=`subMenu('${i}')`) #{i}
また、離れたときに `isOpen` を `''` に戻した方が良いでしょうから、 `@mouseout` というのを用いるといいと思います。

2021-09-17 04:09 UTC, shundroid requested changes

2021-09-17 04:09 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +        li(id="menu")
idはclassと違って複数要素に同じものを指定しないルールとなっているため、ここではclassのほうがいいと思います。
classはpugを使うと、 `li(class="class-test")` を `li.class-test` と書けます。
`li.menu` のようにするとよいと思います。

2021-09-17 04:09 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +            a(href=theme.menu[i].link id="link") #{i}
ここもclassにしてください

2021-09-17 04:09 UTC, shundroid commented on themes/igem-2021/layout/_partial/header.pug
> +              ul(id="submenu" ,:class=`{ active:activeMenu==='${i}'}`)
ここもclassにして、 ``ul.submenu(:class=`...`)`` のように行けないですかね
もし行けなかったら、 ``ul(:class=`{ submenu: true, active: ... }`)`` のようにしてください。

2021-09-17 04:44 UTC, niimi213 commented on themes/igem-2021/layout/_partial/header.pug
> +            a(href=theme.menu[i].link id="link") #{i}
id="link"は消し忘れだったので消します

2021-09-17 05:00 UTC, shundroid approved these changes

2021-09-17 05:00 UTC, shundroid commented
ありがとうございます

2021-09-17 05:00 UTC, merged